-- Core schema for Postgres migration from Airtable

-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

-- Mentors
CREATE TABLE IF NOT EXISTS mentors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  airtable_id TEXT UNIQUE,
  legacy_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  job_title TEXT,
  workplace TEXT,
  about TEXT,
  details TEXT,
  competencies TEXT,
  experience TEXT,
  price TEXT,
  status TEXT NOT NULL,
  email CITEXT,
  preferred_contact TEXT,
  calendar_url TEXT,
  privacy BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER,
  login_token TEXT,
  login_token_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mentors_status_chk CHECK (status IN ('pending', 'active', 'inactive', 'declined'))
);

CREATE UNIQUE INDEX IF NOT EXISTS mentors_legacy_id_uniq ON mentors (legacy_id);
CREATE INDEX IF NOT EXISTS mentors_status_idx ON mentors (status);
CREATE UNIQUE INDEX IF NOT EXISTS mentors_active_email_uniq
  ON mentors (email)
  WHERE status = 'active' AND email IS NOT NULL;
CREATE INDEX IF NOT EXISTS mentors_slug_idx ON mentors (slug);

-- Tags
CREATE TABLE IF NOT EXISTS tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Mentor tags (M:N)
CREATE TABLE IF NOT EXISTS mentor_tags (
  mentor_id UUID NOT NULL REFERENCES mentors(id) ON DELETE CASCADE,
  tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (mentor_id, tag_id)
);

CREATE INDEX IF NOT EXISTS mentor_tags_tag_id_idx ON mentor_tags (tag_id);

-- Client requests
CREATE TABLE IF NOT EXISTS client_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  airtable_id TEXT UNIQUE,
  mentor_id UUID REFERENCES mentors(id) ON DELETE SET NULL,
  email CITEXT,
  name TEXT,
  preferred_contact TEXT,
  description TEXT,
  level TEXT,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_changed_at TIMESTAMPTZ,
  scheduled_at TIMESTAMPTZ,
  decline_reason TEXT,
  decline_comment TEXT,
  CONSTRAINT client_requests_status_chk CHECK (status IN (
    'pending', 'contacted', 'working', 'done', 'reschedule', 'declined', 'unavailable'
  )),
  CONSTRAINT client_requests_decline_reason_chk CHECK (decline_reason IS NULL OR decline_reason IN (
    'no_time', 'topic_mismatch', 'helping_others', 'on_break', 'other'
  ))
);

CREATE INDEX IF NOT EXISTS client_requests_mentor_status_idx ON client_requests (mentor_id, status);
CREATE INDEX IF NOT EXISTS client_requests_status_changed_at_idx ON client_requests (status_changed_at);

-- Reviews
CREATE TABLE IF NOT EXISTS reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  airtable_id TEXT UNIQUE,
  client_request_id UUID NOT NULL UNIQUE REFERENCES client_requests(id) ON DELETE CASCADE,
  complete TEXT,
  helped TEXT,
  one_enough TEXT,
  again TEXT,
  nps TEXT,
  mentor_review TEXT,
  platform_review TEXT,
  improvements TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Moderators
CREATE TABLE IF NOT EXISTS moderators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email CITEXT,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT moderators_role_chk CHECK (role IN ('admin', 'moderator'))
);

-- Updated_at trigger helper
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Updated_at triggers
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mentors_updated_at') THEN
    CREATE TRIGGER trg_mentors_updated_at
    BEFORE UPDATE ON mentors
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_tags_updated_at') THEN
    CREATE TRIGGER trg_tags_updated_at
    BEFORE UPDATE ON tags
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_client_requests_updated_at') THEN
    CREATE TRIGGER trg_client_requests_updated_at
    BEFORE UPDATE ON client_requests
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_reviews_updated_at') THEN
    CREATE TRIGGER trg_reviews_updated_at
    BEFORE UPDATE ON reviews
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_moderators_updated_at') THEN
    CREATE TRIGGER trg_moderators_updated_at
    BEFORE UPDATE ON moderators
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;
