package repository

import (
	"context"
	"fmt"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The generated name-<id> slug is only collision-proof while nothing else can
// hold that string. A mentor may CHOOSE any valid username, including one that
// looks like a future generated slug, so the two namespaces overlap — and a
// caller who omitted the optional username has no way to react to being told
// the name is taken. Whether the retry loop actually sees a live mentors.slug
// is a property of the query it runs, so it needs a real database.
//
// Requires a database (see the dbtest package docs); skips without one.

// nextGeneratedLegacyID reports the legacy_id the next CreateMentor will use.
// mentors.legacy_id is GENERATED BY DEFAULT AS IDENTITY, so every seeded row
// consumes one too — read this AFTER seeding, never before. Peeking without
// consuming is sound only because Go runs a package's tests sequentially, so
// the caller asserts the prediction actually held.
func nextGeneratedLegacyID(t *testing.T, pool *pgxpool.Pool) int {
	t.Helper()
	ctx := context.Background()

	var lastValue int
	var isCalled bool
	require.NoError(t, pool.QueryRow(ctx,
		`SELECT last_value, is_called FROM mentors_legacy_id_seq`).Scan(&lastValue, &isCalled))
	if isCalled {
		return lastValue + 1
	}
	return lastValue
}

// TestCreateMentorRetriesAGeneratedSlugTakenByALiveProfile: the claim check used
// to look only at mentor_slug_history, so a generated slug colliding with a
// mentor's CURRENT slug fell through to the UNIQUE constraint and failed the
// whole registration with ErrSlugTaken — blaming a caller who never chose a
// username. It must disambiguate with the numeric suffix instead.
func TestCreateMentorRetriesAGeneratedSlugTakenByALiveProfile(t *testing.T) {
	repo, pool := updateTestRepo(t)
	ctx := context.Background()

	// Seed first (the insert consumes a legacy_id), then predict, then point the
	// squatter at exactly the slug the next generated one will be.
	squatter := seedMentor(t, pool, "collide-generated-placeholder")
	predictedID := nextGeneratedLegacyID(t, pool)
	collidingSlug := fmt.Sprintf("collide-generated-%d", predictedID)
	_, err := pool.Exec(ctx, `UPDATE mentors SET slug = $1 WHERE id = $2`, collidingSlug, squatter)
	require.NoError(t, err)

	fields := map[string]interface{}{
		"name":   "Collide Generated",
		"status": "draft",
	}
	mentorID, legacyID, generated, err := repo.CreateMentor(ctx, fields, nil)
	require.NoError(t, err, "a generated slug clash must not fail the registration")
	t.Cleanup(func() {
		_, _ = pool.Exec(context.Background(), `DELETE FROM mentors WHERE id = $1`, mentorID)
	})

	require.Equal(t, predictedID, legacyID,
		"the sequence moved under the test, so the collision was never exercised")
	assert.Equal(t, collidingSlug+"-2", generated,
		"the clash must be resolved by the numeric suffix, not by failing")

	var live string
	require.NoError(t, pool.QueryRow(ctx,
		`SELECT slug FROM mentors WHERE id = $1`, mentorID).Scan(&live))
	assert.Equal(t, generated, live, "the stored slug must be the disambiguated one")
}

// A CHOSEN username that collides with a live profile keeps failing: that caller
// picked the name and can pick another. Only the generated path may rewrite.
func TestCreateMentorStillRefusesAChosenSlugTakenByALiveProfile(t *testing.T) {
	repo, pool := updateTestRepo(t)
	ctx := context.Background()

	seedMentor(t, pool, "chosen-collision-target")

	fields := map[string]interface{}{
		"name":   "Chosen Collision",
		"slug":   "chosen-collision-target",
		"status": "draft",
	}
	_, _, _, err := repo.CreateMentor(ctx, fields, nil)
	require.ErrorIs(t, err, ErrSlugTaken)

	var rows int
	require.NoError(t, pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM mentors WHERE name = 'Chosen Collision'`).Scan(&rows))
	assert.Equal(t, 0, rows, "the refused registration must leave no row behind")
}
